[project]
name = "cachr"
version = "0.0.1"
requires-python = ">=3.9"
description = "Library that allows you to compose your own cache, pre-packaged with many useful caches"
authors = [
  {email = "mikehuls42@gmail.com"},
  {name = "Mike Huls"}
]
license = {file = "LICENSE.txt"}
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: Implementation :: CPython",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
]
dynamic = ["version"]
dependencies = []

[project.urls]
"Homepage" = "https://github.com/mike-huls/cachr"
"Bug Tracker" = "https://github.com/mike-huls/cachr/issues"
"Documentation" = "https://github.com/mike-huls/cachr/blob/master/README.md/"
"Source" = "https://github.com/mike-huls/cachr/"
"Say Thanks!" = "https://www.buymeacoffee.com/mikehuls"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Optional: if you want to build a source distribution as well
sdist = true
