[tool.poetry]
name = "cachr"
version = "0.0.8"
description = "Library that allows you to compose your own cache, pre-packaged with many useful caches"
authors = ["Mike Huls <mikehuls42@gmail.com>"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "License :: OSI Approved :: MIT License",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
ruff = "^0.7.2"
coverage = "^7.6.4"
pytest = "^8.3.3"

[project.urls]
"Homepage" = "https://github.com/mike-huls/cachr"
"Bug Tracker" = "https://github.com/mike-huls/cachr/issues"
"Documentation" = "https://github.com/mike-huls/cachr/blob/master/README.md/"
"Source" = "https://github.com/mike-huls/cachr/"
"Say Thanks!" = "https://www.buymeacoffee.com/mikehuls"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Optional: if you want to build a source distribution as well
sdist = true
